version: '3.9'
services:

  account_management:
    container_name: account_service
    build: ./account_management
    environment:
      - DATABASE_URL=postgresql://onlineshop:cloud2024@db:5432/flask_db
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_DB: flask_db
      POSTGRES_USER: onlineshop
      POSTGRES_PASSWORD: cloud2024
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}