services:
  account_management:
    container_name: account_service
    image: account_service:1.0.0
    build: ./account_management
    environment:
      - JWT_SECRET_KEY=nyquist
      - DATABASE_URL=postgresql://onlineshop:cloud2024@db_account:5432/flask_db
    ports:
      - "4001:4000"
    depends_on:
      - db_account

  payment_service:
    container_name: payment_service
    image: payment_service:1.0.0
    build: ./payment_service
    ports:
      - "4002:4000"
    environment:
      - SECRET_KEY=nyquist
      - DEBUG=True
      - URL_PREFIX=/api/payment
      
  purchase_service:
    container_name: purchase_service
    image: purchase-service:1.0.0
    build: ./purchase_service
    ports:
      - "4003:4000"
    # healthcheck:
    #     test: ["CMD", "curl", "-f", "http://localhost:4000/api/purchase"]
    #     interval: 5s
    #     timeout: 5s
    #     retries: 5
    environment:
      - SECRET_KEY=nyquist
      - DEBUG=True
      - URL_PREFIX=/api/purchase
      - SQLALCHEMY_DATABASE_URI=postgresql://onlineshop:cloud2024@db_purchase:5432/flask_db
      - PAYMENT_SERVICE_URL=http://payment_service:4000/api/payment
      - ACCOUNT_SERVICE_URL=http://account_service:4000/api/account
    depends_on:
      - db_purchase

  product_catalog:
    container_name: product_catalog
    image: product_catalog:1.0.0
    build: ./product_catalog
    ports:
      - "4004:4000"
    environment:
      - DB_URL=postgresql://onlineshop:cloud2024@db_product:5432/flask_db
    depends_on:
      - db_product

  shopping_cart:
    container_name: shopping_cart
    image: shopping_cart:1.0.0
    build: ./shopping_cart
    ports:
      - "4005:4000"
    environment:
      - DB_URL=postgresql://onlineshop:cloud2024@db_cart:5432/flask_db
    depends_on:
      - db_cart

  react_app:
    container_name: react_app
    image: frontend:1.0.0
    build: ./react-app
    ports:
      - "8000:8000"

  db_account:
    container_name: db_account
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=flask_db
      - POSTGRES_USER=onlineshop
      - POSTGRES_PASSWORD=cloud2024

  db_purchase:
    container_name: db_purchase
    image: postgres:13
    ports:
      - "5433:5432"
    # healthcheck:
    #   test: ["CMD", "pg_isready"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

    environment:
      - POSTGRES_DB=flask_db
      - POSTGRES_USER=onlineshop
      - POSTGRES_PASSWORD=cloud2024
    
  db_product:
    container_name: db_product
    image: postgres:13
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=flask_db
      - POSTGRES_USER=onlineshop
      - POSTGRES_PASSWORD=cloud2024

  db_cart:
    container_name: db_cart
    image: postgres:13
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=flask_db
      - POSTGRES_USER=onlineshop
      - POSTGRES_PASSWORD=cloud2024
  


