version: '3.9'

services:
  payment-service:
    container_name: payment-service
    image: payment-service:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - SECRET_KEY=nyquist

volumes:
  pgdata: {}