name: Terraform

on:
  workflow_run:
    workflows: ["Tests"]
    types: [completed]
    branches: [main]
    
  workflow_dispatch:

jobs:
  apply_terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Rome"
          timezoneMacos: "Europe/Rome"
          timezoneWindows: "Europe/Rome"

      - name: Update 
        run: sudo apt-get update

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Fetch Terraform state, if exist, from S3
        run: |
          aws s3 cp s3://ebook-store-tfstate/terraform.tfstate terraform/terraform.tfstate || true

      - name: Fetch Terraform variables, 
        run: |
          aws s3 cp s3://ebook-store-tfstate/terraform.tfvars terraform/terraform.tfvars

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve

      - name: Push Terraform state to S3
        run: |
          aws s3 cp terraform/terraform.tfstate s3://ebook-store-tfstate/terraform.tfstate